version: '3.7'

services:
    backend:
      build: ./backend-example-docker
      restart: unless-stopped
      environment:
        - REDIS=redis
        - REDIS_PORT=6379
        - DB_USERNAME=postgres
        - DB_PASSWORD=pass
        - DB_HOST=db
      ports:
        - 8000:8000
      container_name: backend
      depends_on:
        - db

    frontend:
      build: ./frontend-example-docker
      ports:
        - 5000:5000
      container_name: frontend

    redis:
      image: redis
      ports:
        - 6379:6379
      container_name: cache

    db:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=pass
      ports:
        - 5432:5432
      container_name: db
      volumes:
          - pgdata:/var/lib/postgresql/data
volumes:
    pgdata:
        external: true
