version: '3.5' 

services: 
    backend:  
      build: ./backend-example-docker
      ports: 
        - 8000:8000
      container_name: backend
    
    frontend:
      build: ./frontend-example-docker
      ports: 
        - 5000:5000
      container_name: frontend
