version: '3.7' 

services: 
    backend:  
      build: ./backend-example-docker
      restart: unless-stopped
      environment: 
        - REDIS=redis
        - REDIS_PORT=6379
        - DB_USERNAME=postgres
        - DB_PASSWORD=pass
        - DB_HOST=db
      expose:
        - 8000
      container_name: backend
      depends_on: 
        - db

    reverseproxy:
      image: nginx
      restart: unless-stopped
      ports: 
        - 80:80
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - /var/run/docker.sock:/tmp/docker.sock:ro
      depends_on: 
        - backend
        - frontend

    frontend:
      build: ./frontend-example-docker
      expose:
        - 5000
      container_name: frontend

    redis:
      image: redis
      ports:
        - 6379:6379
      container_name: cache

    db:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=pass
      ports:
        - 5432:5432
      container_name: db
