version: '3.5' 
services: 
    backend:  
      build: ./backend-example-docker
      environment: 
        - REDIS=redis
        - REDIS_PORT=6379
      ports: 
        - 8000:8000
      container_name: backend
      links: 
        - redis
      restart: unless-stopped
    frontend:
      build: ./frontend-example-docker
      ports: 
        - 5000:5000
      container_name: frontend
    redis:
      image: redis
      expose:
        - 6379
      container_name: redis